
select e.name as emp_nm,
   d.department_name as dept_nm
from employees e, departments d
where e.department_id = d.department_id;


select e.name as "이름",
   d.department_name as "부서명"
from employees e, departments d
where e.department_id = d.department_id;


SELECT * FROM EMPLOYEES WHERE MANAGER_ID = 123;
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NULL;


SELECT NAME, SALARY 
FROM EMPLOYEES WHERE SALARY > 5000;

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 10;

select * from customers where name like 'C%';

select name
from customers
where name like '%r\%%' escape '\';
#패턴 'r%'를 포함하는 데이터

select name
from customers
where name like '%#_3%' escape '#';
#패턴 '_3'를 포함하는 데이터

select file_name
from FILE_INFO
where file_name like '%\_2026%' escape '\';

select * from employees
where salary not between 3000 and 5000;

select name, email
from customers
where name like '%\%%' escape '\';

SELECT ACCOUNT_ID, BALANCE
FROM ACCOUNTS
WHERE ACCOUNT_TYPE IN ('SAVINGS', 'CREDIT') 
  AND BALANCE BETWEEN 30000 AND 70000;

SELECT TRANSACTION_ID, AMOUNT
FROM TRANSACTIONS
WHERE TRANSACTION_TYPE IN ('DEPOSIT') 
  AND AMOUNT >= 1000;

SELECT LOAN_ID, AMOUNT
FROM LOANS
WHERE STATUS NOT IN ('REJECTED') 
  AND AMOUNT >= 50000;


SELECT NAME, SALARY 
FROM EMPLOYEES
ORDER BY SALARY DESC NULLS LAST;

SELECT NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID ASC, SALARY DESC nulls last;

SELECT NAME, EMAIL
FROM CUSTOMERS
ORDER BY EMAIL ASC NULLS FIRST, NAME ASC;



SELECT NAME, EMAIL
FROM CUSTOMERS
ORDER BY 
    CASE WHEN EMAIL IS NULL THEN 0 ELSE 1 END ASC,
    EMAIL ASC,
    TO_NUMBER(REGEXP_SUBSTR(NAME, '[0-9]+')) ASC;


SELECT *
FROM ACCOUNTS
WHERE BALANCE >= 50000
ORDER BY ACCOUNT_TYPE ASC, BALANCE DESC;

SELECT TRANSACTION_ID, AMOUNT
FROM TRANSACTIONS
ORDER BY TRANSACTION_TYPE ASC, AMOUNT DESC;

SELECT DISTINCT ACCOUNT_TYPE
FROM ACCOUNTS;

SELECT DISTINCT TRANSACTION_TYPE
FROM TRANSACTIONS;

SELECT COUNT(DISTINCT ACCOUNT_TYPE), COUNT(DISTINCT CUSTOMER_ID)
FROM ACCOUNTS
ORDER BY ACCOUNT_TYPE ASC, CUSTOMER_ID ASC;

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY), -1) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID ASC;

SELECT JOB_ID,
    MAX(SALARY) AS MAX_SALARY,
    MIN(SALARY) AS MIN_SALARY
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT SUM(COUNT(*)) AS EMP_COUNT
FROM EMPLOYEES
WHERE SALARY > 5000
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID ASC NULLS LAST;

SELECT SUM(EMP_COUNT) AS EMP_COUNT
FROM (
    SELECT DEPARTMENT_ID, COUNT(*) AS EMP_COUNT
    FROM EMPLOYEES
    WHERE SALARY > 5000
    GROUP BY DEPARTMENT_ID
) subquery
ORDER BY DEPARTMENT_ID ASC NULLS LAST;

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY), -1) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 6000
ORDER BY DEPARTMENT_ID ASC NULLS LAST;

SELECT ACCOUNT_TYPE, ROUND(AVG(BALANCE), -1) AS AVG_BALANCE
FROM ACCOUNTS
GROUP BY ACCOUNT_TYPE
ORDER BY AVG_BALANCE DESC;

SELECT TRANSACTION_TYPE,
    ROUND(SUM(AMOUNT), -1) AS TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY ROLLUP(TRANSACTION_TYPE);

SELECT CUSTOMER_ID,
    COUNT(*) AS ACCOUNT_COUNT,
    ROUND(AVG(BALANCE), -1) AS AVG_BALANCE
FROM ACCOUNTS
GROUP BY CUSTOMER_ID
HAVING AVG(BALANCE) >= 50000
ORDER BY ACCOUNT_COUNT DESC, CUSTOMER_ID ASC;
